name: Docs

on:
  push:
    branches: '*'

jobs:
  docs:
    name: Docs

    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    container: ghcr.io/osgeo/proj-docs

    steps:
    - uses: actions/checkout@v3
    - name: Print versions
      run: |
          python3 --version
          sphinx-build --version
    - name: Lint .rst files
      run: |
        if find . -name '*.rst' | xargs grep -P '\t'; then echo 'Tabs are bad, please use four spaces in .rst files.'; false; fi
    - name: PDF
      run: |
        make latexpdf
    - name: Spelling
      run: |
        make spelling
    - uses: actions/upload-artifact@v4
      with:
        name: PDF
        path: build/latex/LAS.pdf
        if-no-files-found: error
    - uses: actions/upload-artifact@v4
      with:
        name: TEX
        path: build/latex/LAS.tex
        if-no-files-found: error
    - uses: actions/upload-artifact@v4
      with:
        name: Misspelled
        path: build/spelling/output.txt
        if-no-files-found: ignore

